// Landmark vulnerabilities of the last decade (hand-curated).
// Live data (CVSS, CISA KEV, ransomware use, EPSS, public exploits) is added at build time.
// k: category — windows | linux | edge (VPN/firewall/appliance) | web (servers, frameworks, apps) |
//    mail | client (Office, browsers, file formats) | supply | hw | mobile | technique (no CVE)

export const LANDMARKS = [
  { name: 'EternalBlue', cves: ['CVE-2017-0144'], year: 2017, k: 'windows', product: 'Windows SMBv1 (MS17-010)',
    what: 'Remote code execution in the Windows SMBv1 server, leaked by the Shadow Brokers from an NSA toolkit.',
    why: 'Powered WannaCry and NotPetya in 2017 — two of the most destructive cyberattacks ever — and is still used for lateral movement on unpatched networks.' },
  { name: 'BlueKeep', cves: ['CVE-2019-0708'], year: 2019, k: 'windows', product: 'Windows Remote Desktop Services',
    what: 'Pre-authentication, wormable RCE in Remote Desktop on Windows 7, Server 2008 and older.',
    why: 'Microsoft even patched Windows XP; it became the textbook case for never exposing RDP to the internet.' },
  { name: 'Zerologon', cves: ['CVE-2020-1472'], year: 2020, k: 'windows', product: 'Windows Netlogon',
    what: 'A cryptographic flaw in Netlogon lets anyone on the network reset a domain controller’s machine password and take over the domain in seconds.',
    why: 'Turned any foothold into instant domain admin; quickly adopted by ransomware gangs and state actors.' },
  { name: 'PrintNightmare', cves: ['CVE-2021-34527', 'CVE-2021-1675'], year: 2021, k: 'windows', product: 'Windows Print Spooler',
    what: 'Print Spooler lets authenticated users load drivers, giving remote code execution and local privilege escalation to SYSTEM.',
    why: 'A proof of concept leaked before a fix existed; led Microsoft to lock down driver installation for good.' },
  { name: 'HiveNightmare / SeriousSAM', cves: ['CVE-2021-36934'], year: 2021, k: 'windows', product: 'Windows 10/11 registry ACLs',
    what: 'Overly permissive permissions let normal users read the SAM, SYSTEM and SECURITY hives from shadow copies.',
    why: 'Any user could dump local password hashes — a simple, reliable privilege escalation.' },
  { name: 'PetitPotam', cves: ['CVE-2021-36942'], year: 2021, k: 'windows', product: 'Windows LSA / EFSRPC',
    what: 'Forces a Windows server, including a domain controller, to authenticate to an attacker, who relays it to Active Directory Certificate Services.',
    why: 'Made NTLM relay to AD CS a standard path to domain takeover.' },
  { name: 'noPac / sAMAccountName spoofing', cves: ['CVE-2021-42278', 'CVE-2021-42287'], year: 2021, k: 'windows', product: 'Active Directory',
    what: 'Two flaws combined let any domain user impersonate a domain controller and obtain its Kerberos tickets.',
    why: 'Standard domain user to domain admin in one step.' },
  { name: 'Certifried', cves: ['CVE-2022-26923'], year: 2022, k: 'windows', product: 'Active Directory Certificate Services',
    what: 'A certificate template flaw lets a normal user obtain a certificate for a domain controller.',
    why: 'Another short path from user to domain admin through AD CS.' },
  { name: 'SMBGhost', cves: ['CVE-2020-0796'], year: 2020, k: 'windows', product: 'Windows SMBv3 compression',
    what: 'Wormable RCE in SMBv3 compression on Windows 10 and Server 2019.',
    why: 'Revived fears of an EternalBlue-style worm; widely used for local privilege escalation.' },
  { name: 'SIGRed', cves: ['CVE-2020-1350'], year: 2020, k: 'windows', product: 'Windows DNS Server',
    what: 'A 17-year-old wormable RCE in Windows DNS Server, which usually runs on domain controllers.',
    why: 'CVSS 10 and domain-controller impact made it an emergency patch for every Windows shop.' },
  { name: 'CurveBall', cves: ['CVE-2020-0601'], year: 2020, k: 'windows', product: 'Windows CryptoAPI',
    what: 'A flaw in elliptic-curve certificate validation lets attackers spoof code-signing and TLS certificates.',
    why: 'Reported to Microsoft by the NSA — one of the first times it publicly disclosed such a bug.' },
  { name: 'Dirty COW', cves: ['CVE-2016-5195'], year: 2016, k: 'linux', product: 'Linux kernel',
    what: 'A race condition in copy-on-write memory handling lets local users write to read-only files and become root.',
    why: 'Present for nine years; used to root Android phones and countless Linux servers.' },
  { name: 'Dirty Pipe', cves: ['CVE-2022-0847'], year: 2022, k: 'linux', product: 'Linux kernel 5.8+',
    what: 'A pipe-buffer flag bug lets unprivileged users overwrite data in read-only files, including root-owned ones.',
    why: 'Trivial, reliable local root on modern kernels and Android devices.' },
  { name: 'PwnKit', cves: ['CVE-2021-4034'], year: 2022, k: 'linux', product: 'polkit pkexec',
    what: 'Memory corruption in pkexec, installed by default on almost every Linux distribution, gives local root.',
    why: 'Present since 2009 and exploitable in seconds on nearly every Linux desktop and server.' },
  { name: 'Baron Samedit', cves: ['CVE-2021-3156'], year: 2021, k: 'linux', product: 'sudo',
    what: 'A heap overflow in sudo lets any local user gain root, even without being listed in sudoers.',
    why: 'Hidden in sudo for about ten years; affected most Linux and many Unix systems.' },
  { name: 'Looney Tunables', cves: ['CVE-2023-4911'], year: 2023, k: 'linux', product: 'glibc dynamic loader',
    what: 'A buffer overflow in glibc’s handling of GLIBC_TUNABLES gives local root on major distributions.',
    why: 'Quickly weaponised by cloud-focused threat actors.' },
  { name: 'regreSSHion', cves: ['CVE-2024-6387'], year: 2024, k: 'linux', product: 'OpenSSH server',
    what: 'A signal-handler race in sshd allows unauthenticated remote code execution as root on glibc Linux.',
    why: 'A regression of a 2006 bug in one of the most exposed services on the internet.' },
  { name: 'XZ Utils backdoor', cves: ['CVE-2024-3094'], year: 2024, k: 'supply', product: 'xz / liblzma',
    what: 'A maintainer account built trust for two years, then shipped a backdoor that targeted OpenSSH through liblzma.',
    why: 'Caught by chance days before reaching stable distributions — the defining open-source supply-chain scare.' },
  { name: 'Log4Shell', cves: ['CVE-2021-44228'], year: 2021, k: 'web', product: 'Apache Log4j 2',
    what: 'Logging an attacker-controlled string triggers a JNDI lookup that loads remote code.',
    why: 'Log4j was embedded almost everywhere; mass exploitation began within hours and patching took years.' },
  { name: 'Equifax Struts bug', cves: ['CVE-2017-5638'], year: 2017, k: 'web', product: 'Apache Struts 2',
    what: 'A malformed Content-Type header gives remote code execution in Struts 2 web apps.',
    why: 'Exploited in the Equifax breach, exposing data on about 147 million people.' },
  { name: 'Spring4Shell', cves: ['CVE-2022-22965'], year: 2022, k: 'web', product: 'Spring Framework',
    what: 'Data binding on JDK 9+ allows remote code execution in Spring MVC applications on Tomcat.',
    why: 'Leaked before disclosure; a scare comparable to Log4Shell, though narrower in practice.' },
  { name: 'Ghostcat', cves: ['CVE-2020-1938'], year: 2020, k: 'web', product: 'Apache Tomcat AJP',
    what: 'The AJP connector lets attackers read web-app files and, in some setups, execute code.',
    why: 'AJP was enabled by default for years, so the exposure was enormous.' },
  { name: 'Confluence OGNL injection', cves: ['CVE-2022-26134'], year: 2022, k: 'web', product: 'Atlassian Confluence',
    what: 'Unauthenticated OGNL injection gives remote code execution on Confluence Server and Data Center.',
    why: 'Exploited as a zero-day and then en masse by cryptominers and ransomware groups.' },
  { name: 'MOVEit Transfer', cves: ['CVE-2023-34362'], year: 2023, k: 'web', product: 'Progress MOVEit Transfer',
    what: 'SQL injection in the file-transfer web app lets attackers steal stored files.',
    why: 'Cl0p hit thousands of organisations and tens of millions of people in one data-theft campaign.' },
  { name: 'Kaseya VSA', cves: ['CVE-2021-30116'], year: 2021, k: 'supply', product: 'Kaseya VSA',
    what: 'Credential-leak flaws in the remote-management platform used by managed service providers.',
    why: 'REvil pushed ransomware through MSPs to around 1,500 businesses at once.' },
  { name: 'ScreenConnect auth bypass', cves: ['CVE-2024-1709', 'CVE-2024-1708'], year: 2024, k: 'web', product: 'ConnectWise ScreenConnect',
    what: 'The setup wizard could be re-run to create an admin account; combined with path traversal for code execution.',
    why: 'Trivially exploitable remote-access software — immediately used by ransomware groups.' },
  { name: 'Jenkins file read', cves: ['CVE-2024-23897'], year: 2024, k: 'web', product: 'Jenkins',
    what: 'The command-line parser lets unauthenticated users read files on the server, often leading to code execution.',
    why: 'Exposed CI servers hold the keys to entire software pipelines.' },
  { name: 'ProxyLogon', cves: ['CVE-2021-26855', 'CVE-2021-27065'], year: 2021, k: 'mail', product: 'Microsoft Exchange Server',
    what: 'An SSRF plus a file-write flaw give unauthenticated remote code execution on on-premises Exchange.',
    why: 'Exploited by HAFNIUM and then by many groups; tens of thousands of servers were backdoored.' },
  { name: 'ProxyShell', cves: ['CVE-2021-34473', 'CVE-2021-34523', 'CVE-2021-31207'], year: 2021, k: 'mail', product: 'Microsoft Exchange Server',
    what: 'A chain of three flaws gives unauthenticated remote code execution on Exchange.',
    why: 'Became a favourite ransomware entry point through 2021 and 2022.' },
  { name: 'ProxyNotShell', cves: ['CVE-2022-41040', 'CVE-2022-41082'], year: 2022, k: 'mail', product: 'Microsoft Exchange Server',
    what: 'An authenticated SSRF plus PowerShell remote code execution on Exchange.',
    why: 'Exploited as zero-days for weeks while the first mitigations were bypassed.' },
  { name: 'Outlook NTLM leak', cves: ['CVE-2023-23397'], year: 2023, k: 'mail', product: 'Microsoft Outlook',
    what: 'A crafted reminder makes Outlook send the user’s NTLM hash to an attacker — with no click needed.',
    why: 'Used by Russia’s APT28 against European government and energy targets.' },
  { name: 'Barracuda ESG', cves: ['CVE-2023-2868'], year: 2023, k: 'edge', product: 'Barracuda Email Security Gateway',
    what: 'Command injection when scanning attachments of incoming email.',
    why: 'Exploited by China-linked UNC4841; Barracuda told customers to replace the appliances outright.' },
  { name: 'Citrix ADC path traversal (“Shitrix”)', cves: ['CVE-2019-19781'], year: 2019, k: 'edge', product: 'Citrix ADC / Gateway',
    what: 'Directory traversal gives unauthenticated remote code execution on Citrix ADC and Gateway.',
    why: 'Mass-exploited in early 2020 and later used in ransomware attacks.' },
  { name: 'Citrix Bleed', cves: ['CVE-2023-4966'], year: 2023, k: 'edge', product: 'Citrix NetScaler ADC / Gateway',
    what: 'A memory leak exposes session tokens, letting attackers hijack authenticated sessions and bypass MFA.',
    why: 'Used by LockBit affiliates against large organisations, including Boeing.' },
  { name: 'FortiOS SSL-VPN credential leak', cves: ['CVE-2018-13379'], year: 2019, k: 'edge', product: 'Fortinet FortiOS SSL-VPN',
    what: 'Path traversal lets anyone download the file holding VPN users’ session credentials.',
    why: 'Credentials for tens of thousands of VPNs were later dumped online; exploited for years.' },
  { name: 'FortiOS auth bypass', cves: ['CVE-2022-40684'], year: 2022, k: 'edge', product: 'Fortinet FortiOS / FortiProxy',
    what: 'A crafted HTTP request bypasses authentication on the admin interface.',
    why: 'Full firewall takeover; exploited within days of the fix.' },
  { name: 'Pulse Secure VPN file read', cves: ['CVE-2019-11510'], year: 2019, k: 'edge', product: 'Pulse Connect Secure',
    what: 'Unauthenticated arbitrary file read on the VPN, exposing credentials and session data.',
    why: 'One of the most exploited VPN bugs ever, including in ransomware attacks.' },
  { name: 'Ivanti Connect Secure chain', cves: ['CVE-2023-46805', 'CVE-2024-21887'], year: 2024, k: 'edge', product: 'Ivanti Connect Secure',
    what: 'An authentication bypass chained with command injection gives unauthenticated control of the VPN.',
    why: 'Exploited by China-linked actors; CISA ordered US agencies to disconnect affected appliances.' },
  { name: 'PAN-OS GlobalProtect', cves: ['CVE-2024-3400'], year: 2024, k: 'edge', product: 'Palo Alto Networks PAN-OS',
    what: 'Command injection in the GlobalProtect gateway gives unauthenticated root on the firewall.',
    why: 'CVSS 10, exploited as a zero-day before disclosure.' },
  { name: 'F5 BIG-IP TMUI', cves: ['CVE-2020-5902'], year: 2020, k: 'edge', product: 'F5 BIG-IP',
    what: 'Remote code execution in the Traffic Management User Interface.',
    why: 'Mass scanning began within days on devices that sit in front of critical apps.' },
  { name: 'F5 iControl REST bypass', cves: ['CVE-2022-1388'], year: 2022, k: 'edge', product: 'F5 BIG-IP',
    what: 'Authentication bypass in the iControl REST API gives root command execution.',
    why: 'Exploits circulated within days; destructive attacks wiped devices.' },
  { name: 'Cisco IOS XE web UI', cves: ['CVE-2023-20198'], year: 2023, k: 'edge', product: 'Cisco IOS XE',
    what: 'The web UI lets unauthenticated attackers create a privilege-15 administrator account.',
    why: 'Tens of thousands of switches and routers were implanted within days.' },
  { name: 'ESXiArgs', cves: ['CVE-2021-21974'], year: 2023, k: 'edge', product: 'VMware ESXi (OpenSLP)',
    what: 'A heap overflow in ESXi’s OpenSLP service gives remote code execution.',
    why: 'Two years after the fix, the ESXiArgs ransomware campaign encrypted thousands of exposed hypervisors.' },
  { name: 'vCenter upload RCE', cves: ['CVE-2021-21972'], year: 2021, k: 'edge', product: 'VMware vCenter Server',
    what: 'An unauthenticated file upload in a vCenter plugin gives remote code execution.',
    why: 'vCenter controls the whole virtual estate; a prized ransomware target.' },
  { name: 'Office Equation Editor', cves: ['CVE-2017-11882'], year: 2017, k: 'client', product: 'Microsoft Office',
    what: 'A stack overflow in the 17-year-old Equation Editor runs code when a document opens.',
    why: 'Among the most exploited vulnerabilities for years in phishing campaigns.' },
  { name: 'Follina', cves: ['CVE-2022-30190'], year: 2022, k: 'client', product: 'Windows MSDT',
    what: 'A Word document can call the Microsoft Support Diagnostic Tool to run code — even with macros disabled.',
    why: 'Exploited as a zero-day, including by state actors; bypassed years of macro hardening.' },
  { name: 'WinRAR spoofed extension', cves: ['CVE-2023-38831'], year: 2023, k: 'client', product: 'RARLAB WinRAR',
    what: 'Opening a harmless-looking file inside an archive runs a hidden script with the same name.',
    why: 'Exploited by criminals against traders and by several state-backed groups.' },
  { name: 'FORCEDENTRY', cves: ['CVE-2021-30860'], year: 2021, k: 'mobile', product: 'Apple iOS (CoreGraphics)',
    what: 'A zero-click iMessage exploit abusing a PDF/JBIG2 integer overflow.',
    why: 'Used by NSO Group’s Pegasus; described by Google as one of the most sophisticated exploits ever seen.' },
  { name: 'libwebp / BLASTPASS', cves: ['CVE-2023-4863', 'CVE-2023-41064'], year: 2023, k: 'mobile', product: 'libwebp · Apple ImageIO',
    what: 'A heap overflow in WebP image decoding, exploited zero-click through iMessage.',
    why: 'Delivered Pegasus spyware and affected every browser and app that renders WebP images.' },
  { name: 'Meltdown', cves: ['CVE-2017-5754'], year: 2018, k: 'hw', product: 'Intel and some Arm CPUs',
    what: 'Speculative execution lets a program read kernel memory.',
    why: 'Forced operating-system redesigns (KPTI) and changed how CPUs are built.' },
  { name: 'Spectre', cves: ['CVE-2017-5753', 'CVE-2017-5715'], year: 2018, k: 'hw', product: 'Most modern CPUs',
    what: 'Speculative execution tricks other programs into leaking their memory through side channels.',
    why: 'A whole new class of hardware bugs that is still producing variants.' },
  { name: 'KRACK', cves: ['CVE-2017-13077'], year: 2017, k: 'hw', product: 'WPA2 Wi-Fi protocol',
    what: 'Key reinstallation attacks against the WPA2 handshake allow decrypting Wi-Fi traffic.',
    why: 'A flaw in the Wi-Fi standard itself, affecting virtually every device.' },
  // 2025
  { name: 'ToolShell', cves: ['CVE-2025-53770'], year: 2025, k: 'web', product: 'Microsoft SharePoint Server (on-premises)',
    what: 'Unsafe deserialization gives unauthenticated remote code execution on on-premises SharePoint; a variant that bypassed the earlier fixes for CVE-2025-49704 and CVE-2025-49706.',
    why: 'Mass-exploited as a zero-day in July 2025, including by China-linked groups and ransomware operators; attackers stole machine keys so access survived patching.' },
  { name: 'CitrixBleed 2', cves: ['CVE-2025-5777'], year: 2025, k: 'edge', product: 'Citrix NetScaler ADC / Gateway',
    what: 'Insufficient input validation lets unauthenticated attackers read memory from the appliance, leaking session tokens.',
    why: 'A near-repeat of 2023’s Citrix Bleed: stolen sessions bypass MFA, and it was exploited in the wild within weeks.' },
  { name: 'SAP NetWeaver Visual Composer upload', cves: ['CVE-2025-31324'], year: 2025, k: 'web', product: 'SAP NetWeaver Visual Composer',
    what: 'A missing authorization check in the Metadata Uploader lets unauthenticated attackers upload files and run code.',
    why: 'CVSS 10 on systems that run core business processes; exploited as a zero-day in 2025, including by China-linked actors.' },
  { name: 'IngressNightmare', cves: ['CVE-2025-1974'], year: 2025, k: 'web', product: 'Kubernetes ingress-nginx',
    what: 'Configuration injection through the ingress-nginx admission controller gives unauthenticated remote code execution.',
    why: 'The controller can read every secret in the cluster, so exposure could mean full Kubernetes cluster takeover.' },
  { name: 'Ivanti Connect Secure overflow', cves: ['CVE-2025-0282'], year: 2025, k: 'edge', product: 'Ivanti Connect Secure',
    what: 'A stack-based buffer overflow gives unauthenticated remote code execution on the VPN appliance.',
    why: 'Exploited as a zero-day in January 2025 by China-linked actors — Ivanti VPNs again, a year after the 2024 chain.' },
  { name: 'CLFS ransomware zero-day', cves: ['CVE-2025-29824'], year: 2025, k: 'windows', product: 'Windows Common Log File System driver',
    what: 'A use-after-free in the CLFS kernel driver lets a local user gain SYSTEM privileges.',
    why: 'Exploited as a zero-day in ransomware attacks in 2025 — part of a long run of CLFS privilege-escalation zero-days.' },
  { name: 'Erlang/OTP SSH', cves: ['CVE-2025-32433'], year: 2025, k: 'web', product: 'Erlang/OTP SSH server',
    what: 'The SSH daemon processes protocol messages before authentication, allowing unauthenticated remote code execution.',
    why: 'CVSS 10 in a component embedded in telecom and networking equipment; public exploits appeared within days.' },
  // Techniques Microsoft treats as by design, so they have no CVE.
  { name: 'Potato family (RottenPotato → GodPotato)', cves: [], year: 2016, k: 'technique', product: 'Windows SeImpersonatePrivilege',
    what: 'A series of tools — RottenPotato (2016), JuicyPotato (2018), RoguePotato and PrintSpoofer (2020), GodPotato (2023) — that trick SYSTEM into authenticating to the attacker and then impersonate that token.',
    why: 'Any service account with SeImpersonatePrivilege (IIS, SQL Server) can become SYSTEM. Microsoft treats it as by design, so each new variant keeps working.',
    links: [['GodPotato', 'https://github.com/BeichenDream/GodPotato'], ['RoguePotato', 'https://github.com/antonioCoco/RoguePotato'], ['PrintSpoofer', 'https://github.com/itm4n/PrintSpoofer']] },
  { name: 'Kerberos relay / KrbRelayUp', cves: [], year: 2022, k: 'technique', product: 'Active Directory (LDAP signing off)',
    what: 'Relays Kerberos authentication to LDAP to set up resource-based constrained delegation on the local machine.',
    why: 'A universal local privilege escalation on domain-joined Windows where LDAP signing is not enforced.',
    links: [['KrbRelayUp', 'https://github.com/Dec0ne/KrbRelayUp']] },
];
